// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP23qRPIJ4Nu7gSgaB5Y4wgiXlIzJC3n4',
    appId: '1:461841345342:web:b3d101fc90de414723da6f',
    messagingSenderId: '461841345342',
    projectId: 'biv-manager',
    authDomain: 'biv-manager.firebaseapp.com',
    storageBucket: 'biv-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAok26cXaV8GKxRt7ScFgLJ2i0i0dLHLYc',
    appId: '1:461841345342:android:0aa8a970d861204623da6f',
    messagingSenderId: '461841345342',
    projectId: 'biv-manager',
    storageBucket: 'biv-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6lqj2C8uX8KzBAR-3mdxERt9oJIMvFw4',
    appId: '1:461841345342:ios:ee74d756291820ba23da6f',
    messagingSenderId: '461841345342',
    projectId: 'biv-manager',
    storageBucket: 'biv-manager.firebasestorage.app',
    iosBundleId: 'com.example.bivManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6lqj2C8uX8KzBAR-3mdxERt9oJIMvFw4',
    appId: '1:461841345342:ios:ee74d756291820ba23da6f',
    messagingSenderId: '461841345342',
    projectId: 'biv-manager',
    storageBucket: 'biv-manager.firebasestorage.app',
    iosBundleId: 'com.example.bivManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP23qRPIJ4Nu7gSgaB5Y4wgiXlIzJC3n4',
    appId: '1:461841345342:web:8ce7d7cfa99aeb1223da6f',
    messagingSenderId: '461841345342',
    projectId: 'biv-manager',
    authDomain: 'biv-manager.firebaseapp.com',
    storageBucket: 'biv-manager.firebasestorage.app',
  );

}