import 'firebase_options.dart';
import 'biv_manager_app.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import 'package:core/di/injection_container.dart' as di;

/// Package-scaffold app entry point.
///
/// In this workspace, the runnable application entry point is `/lib/main.dart`.
/// This file is kept to match the Melos package scaffold structure and may be
/// regenerated by tooling.
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await di.init();

  runApp(const MyApp());
}

/// Scaffold app widget kept for package structure compatibility.
class MyApp extends StatelessWidget {
  /// Constructor
  const MyApp({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return BivManagerApp(
      routerConfig: _ScaffoldRouterConfig.instance,
    );
  }
}

/// Reuses a simple router instance for the package scaffold entrypoint.
class _ScaffoldRouterConfig {
  static final GoRouter instance = GoRouter(
    routes: [
      GoRoute(
        path: '/',
        builder: (context, state) => const Scaffold(
          body: Center(
            child: Text('Use the root /lib/main.dart to run the full app.'),
          ),
        ),
      ),
    ],
  );
}
